#!/usr/bin/env python3
import argparse
import os
import shutil
import subprocess
import sys
import glob

BUILD_DIR = "build"

def run_command(command, check=True):
    try:
        subprocess.run(command, shell=True, check=check)
    except subprocess.CalledProcessError as e:
        print(f"Error executing command: {command}")
        sys.exit(e.returncode)

def clean():
    print("Deleting build folders")
    if os.path.exists(BUILD_DIR):
        shutil.rmtree(BUILD_DIR)
    if os.path.exists("output"):
        shutil.rmtree("output")
    for db_file in glob.glob("*.db"):
        os.remove(db_file)

def configure(build_examples=False):
    if not os.path.exists(BUILD_DIR):
        os.makedirs(BUILD_DIR)
    
    cmd = f'cmake -G "Ninja" -S . -B {BUILD_DIR}'
    if build_examples:
        cmd += " -DBUILD_EXAMPLES=yes -DCMAKE_BUILD_TYPE=Debug"
    
    run_command(cmd)

def build(target=None):
    cmd = f"cmake --build {BUILD_DIR}"
    if target:
        cmd += f" --target {target}"
    
    run_command(cmd)

def main():
    parser = argparse.ArgumentParser(description="Build and clean your project.", add_help=False)
    parser.add_argument("-h", "--help", action="store_true", help="Show this help message and exit.")
    parser.add_argument("-c", "--clean", action="store_true", help="Delete build folders.")
    parser.add_argument("-es", "--examples", action="store_true", help="Build all examples.")
    parser.add_argument("-e", "--example", type=str, help="Build a specific example.")

    args, unknown = parser.parse_known_args()

    if args.help:
        parser.print_help()
        sys.exit(0)

    if args.clean:
        clean()
        sys.exit(0)

    if args.examples:
        configure(build_examples=True)
        build()
    elif args.example:
        configure(build_examples=True)
        build(target=args.example)
    else:
        configure(build_examples=False)
        build()

if __name__ == "__main__":
    main()
